# Documentação do Notebook

## Introdução

Este notebook foi desenvolvido para gerar gráficos a partir de várias simulações do muar.py . Ele está organizado para facilitar a execução e a compreensão dos resultados obtidos. Esta documentação fornecerá todas as informações necessárias para que você possa rodar o notebook corretamente e entender sua estrutura.

## Autor

Rodrigo Flexa  
Email: rodrigoflexa0211@gmail.com

## Requisitos

Para executar este notebook, você precisará ter instalados os seguintes pacotes:

- Python 3.x
- Jupyter Notebook
- Matplotlib
- Pandas
- Plotly
- Glob
- Typing


### Instalação via pip

Para instalar os pacotes necessários utilizando `pip`, você pode usar os seguintes comandos:

```bash
pip install matplotlib pandas plotly glob2

```
### Instalação via anaconda

Para instalar os pacotes necessários utilizando `conda`, você deve ter algum amabiente com o anaconda já instalado com o pyrthon 3.x ou então criar um do zero com os seguinte comando:

```bash
conda create -n meu_ambiente python=3.x
conda activate meu_ambiente
conda install matplotlib pandas plotly
pip install glob2
```


## Conteúdo

Esse notebook propõe uma análise dos resultados de métricas voltadas para as ferramentas 
de bitrate adaptativo, latência temporária, resiliência e também métricas usuais da simulação,
tais como consumo de cpu, cache, banda, reúso e etc, compondo portanto os seguintes gráficos:


- [Gráfico 1](#gr1): Eixo x porcentagem de confiabilidade, Eixo y métricas usuais da simulação inteira (Não ao longo do tempo)

- [Gráfico 2](#gr2): Eixo x Número de servidores derrubados. Eixo y métricas usuais

- [Gráfico 3](#gr3): Bit rate médio por sessão. Bit rate médio por usuário. Bit rate de usuários com conteúdo adaptado

- [Gráfico 4](#gr4): Avaliar usuários bem servidos. Colocar confiabilidade. 
Eixo y usuários bem e mal servidos. Eixo x um com % de confiabilidade e outro com quantidade de servidores derrubados


## Observações

- Esse notebook trabalha com um número fixo de usuários e também de sessões, variando apenas a confiabilidade dos servidores.

### Configuração inicial

Importando bibliotecas necessárias

In [2]:
import glob
import os
import pandas as pd

# import seaborn as sns
# import plotly.graph_objects as go
# import plotly.io as pio
# import plotly.express as px


import warnings

warnings.filterwarnings("ignore")
warnings.simplefilter("ignore")

### Carregamento dos dados

In [3]:
results_flows_directories = glob.glob(
    "../../results/results_flows*/*"
)  # Caso mude a estrutura dos diretórios, esse caminho deve ser alterado
results_flows_directories

['../../results/results_flows/msf_s_50_p_4_sfc_on_rel_0.95',
 '../../results/results_flows/musfico_s_50_p_4_sfc_on_rel_0.975',
 '../../results/results_flows/ga_s_50_p_4_sfc_on_rel_0.99',
 '../../results/results_flows/osfem_s_50_p_4_sfc_on_rel_0.975',
 '../../results/results_flows/ga_s_50_p_4_sfc_on_rel_0.95',
 '../../results/results_flows/msf_s_50_p_4_sfc_on_rel_0.975',
 '../../results/results_flows/musfico_s_50_p_4_sfc_on_rel_0.99',
 '../../results/results_flows/osfem_s_50_p_4_sfc_on_rel_0.95',
 '../../results/results_flows/ga_s_50_p_4_sfc_on_rel_0.975',
 '../../results/results_flows/osfem_s_50_p_4_sfc_on_rel_0.99',
 '../../results/results_flows/musfico_s_50_p_4_sfc_on_rel_0.95',
 '../../results/results_flows/msf_s_50_p_4_sfc_on_rel_0.99']

### Função de coleta dos dados

Essa função irá basicamente métricas selecioandas e concatenar os csv's da simulação verticalmente, recortando as simulações no tempo 0 até 999.

Como os dados estarão concatenados, precisaremos posteriormente retirar uma média dessas simulações

In [25]:
aggregated_simulation_data = pd.DataFrame()


def collect_data_from_alg_directory(results_flows_directories, metricas_de_coleta):
    data_nla = []
    log_simu = {}  # Essa variável serve apenas para verificar as simulações

    for alg_dir in results_flows_directories:
        simulacoes_okays = 0
        simu_exec_name = alg_dir.split("/")[-1].split("_")
        # print(simu_exec_name)
        alg_name = simu_exec_name[0]
        reliability = simu_exec_name[-1]

        files = os.listdir(alg_dir)
        # print(f"Simulação: {alg_name}, {reliability}")
        # print("Quantidade de csv: ", len(files))

        if alg_name not in log_simu:
            log_simu[alg_name] = {
                "reliability": [reliability],
                "files": len(files),
                "simulacoes_sucesso": 0,
                "Nulos": 0,
            }
        else:
            log_simu[alg_name]["reliability"].append(reliability)
            log_simu[alg_name]["files"] += len(files)

        for file in files:
            data_path = os.path.join(alg_dir, file)
            try:
                simulation_df = pd.read_csv(data_path)
                print(simulation_df)
            except Exception as e:
                print(f"Erro ao ler o arquivo {file}: {e}")
                continue

            primeiro_tempo = simulation_df["timestamp"].values[0]
            simulation_df["tempo"] = simulation_df[["timestamp"]].applymap(
                lambda x: x - primeiro_tempo
            )
            simulation_is_success = "sfc_cache_p4_50" in simulation_df["sfc_id"].values

            if simulation_is_success:
                simulacoes_okays += 1
                simulation_df = simulation_df[metricas_de_coleta]

                # Arredondar tempo
                simulation_df["tempo"] = simulation_df["tempo"].astype(int)
                simulation_df = simulation_df.replace("None", pd.NA)

                latency_col = simulation_df[["tempo", "latency"]]
                latency_col.dropna(inplace=True)
                latency_col.loc[:, "latency"] = latency_col["latency"].astype(float)

                # Calcular média acumulada de 'success'
                cumulative_sum_success = 0
                cumulative_avg_success = []
                for i, value in enumerate(simulation_df["success"]):
                    cumulative_sum_success += value
                    cumulative_avg_success.append(cumulative_sum_success / (i + 1))
                simulation_df["success"] = cumulative_avg_success

                simulation_df = simulation_df.groupby("tempo", as_index=False).mean(
                    numeric_only=True
                )
                latency_df = (
                    latency_col.groupby("tempo", as_index=False)
                    .mean(numeric_only=True)
                    .reset_index()
                )

                tempo_range = simulation_df["tempo"].max()
                df_mean = simulation_df.set_index("tempo").reindex(range(tempo_range + 1))
                df_mean = df_mean.fillna(method="ffill")
                df_mean = df_mean.reset_index()

                latency_df = latency_df.set_index("tempo").reindex(range(tempo_range + 1))
                latency_df = latency_df.fillna(method="ffill")
                latency_df = latency_df.reset_index()

                df_mean["latency"] = latency_df["latency"]
                df_mean["algorithm"] = alg_name
                df_mean["reliability"] = reliability
                df_mean = df_mean.iloc[0:1000]
                data_nla.append(df_mean)

        log_simu[alg_name]["simulacoes_sucesso"] += simulacoes_okays
        log_simu[alg_name]["Nulos"] += sum(simulation_df.isnull().sum())

    if data_nla:
        data_nla_f = pd.concat(data_nla)
    else:
        data_nla_f = pd.DataFrame()

    print("\nResumo das Simulações:")
    for alg, info in log_simu.items():
        print(f"Algoritmo: {alg}")
        print(f"  Confiabilidades: {info['reliability']}")
        print(f"  Quantidade de arquivos: {info['files']}")
        print(f"  Simulações de sucesso: {info['simulacoes_sucesso']}")
        print(f"  Dados nulos: {info['Nulos']}")
        print()

    return data_nla_f

### Uso da função de coleta dos dados

Selecione quais métricas (colunas) serão coletadas com base no csv flows.

In [26]:
metricas_de_coleta = [
    "tempo",
    "cpu_utilization",
    "cache_utilization",
    "bandwidth_utilization",
    "cpu_resilient",
    "cache_resilient",
    "bw_resilient",
    "success",
    "latency",
    "duration",
    "running_sfcs",
    "running_players",
    "running_sessions",
    "cpu_saved",
    "cache_saved",
    "shared_vnfs",
    "server_crashed",
]

In [27]:
aggregated_simulation_data = collect_data_from_alg_directory(
    results_flows_directories, metricas_de_coleta
)

      No.          time  timestamp  number_of_sfc  cpu_utilization  \
1     NaN  1.718900e+09          4         0.0103           0.0617
2     NaN  1.718900e+09          4         0.0317           0.1900
3     NaN  1.718900e+09          4         0.0333           0.2000
4     NaN  1.718900e+09          4         0.0547           0.3283
5     NaN  1.718900e+09          4         0.0564           0.3383
...   ...           ...        ...            ...              ...
1321  NaN  1.718901e+09          4         0.7029           0.7029
1322  NaN  1.718901e+09          4         0.7054           0.7054
1323  NaN  1.718901e+09          4         0.7375           0.7375
1324  NaN  1.718901e+09          4         0.7400           0.7400
1325  NaN  1.718901e+09          4         0.7400           0.7400

      cpu_active_servers  bandwidth_utilization  bw_active_links  \
1                 0.0156                 0.1362           0.0333
2                 0.0467                 0.4085           0.0333
3                 0.0485                 0.4247           0.0333
4                 0.0797                 0.6970           0.0333
5                 0.0815                 0.7132           0.0333
...                  ...                    ...              ...
1321              0.2497                 0.5141           0.5000
1322              0.2515                 0.5179           0.5000
1323              0.2663                 0.5483           0.5000
1324              0.2737                 0.5635           0.5000
1325              0.2737                 0.5635           0.5000

      cache_utilization  cache_active_servers  ...       depart_time  \
1                0.4000                0.0103  ...    sfc_cache_p1_1
2                0.4000                0.0317  ...   sfc_unique_p1_1
3                0.4000                0.0333  ...    sfc_cache_p2_1
4                0.4000                0.0547  ...   sfc_unique_p2_1
5                0.4000                0.0564  ...    sfc_cache_p3_1
...                 ...                   ...  ...               ...
1321             0.5714                0.4686  ...  sfc_unique_p2_50
1322             0.5714                0.4703  ...   sfc_cache_p3_50
1323             0.5714                0.4917  ...  sfc_unique_p3_50
1324             0.5714                0.4933  ...   sfc_cache_p4_50
1325             0.5714                0.4933  ...  sfc_unique_p4_50

         sfc_id  cpu_saved  cache_saved  shared_vnfs  running_sfcs  \
1      0.000000        0.0            0            1             1
2      0.000000        0.0            1            2             1
3     10.333333       40.0            4            3             2
4     10.333333       40.0            5            4             2
5     20.666667       80.0            8            5             3
...         ...        ...          ...          ...           ...
1321  46.666667      160.0           22           31            19
1322  57.000000      200.0           25           32            20
1323  57.000000      200.0           26           33            20
1324  67.333333      240.0           29           34            21
1325  67.333333      240.0           29           34            21

      running_players running_sessions  server_crashed  trascode_bw
1                   1                0       32.333333            0
2                   1                0       64.666667            0
3                   1                0       32.333333            0
4                   1                0       64.666667            0
5                   1                0       32.333333            0
...               ...              ...             ...          ...
1321                6                0       64.666667           14
1322                6                0       32.333333           14
1323                6                0       64.666667           14
1324                6                0       32.333333           14
1325                6                0       64.666667           14

[1325 rows x 27 columns]
      No.          time  timestamp  number_of_sfc  cpu_utilization  \
1     NaN  1.718900e+09          4         0.0103           0.0617
2     NaN  1.718900e+09          4         0.0317           0.1900
3     NaN  1.718900e+09          4         0.0333           0.2000
4     NaN  1.718900e+09          4         0.0547           0.3283
5     NaN  1.718900e+09          4         0.0564           0.3383
...   ...           ...        ...            ...              ...
1280  NaN  1.718901e+09          4         0.4977           0.4977
1281  NaN  1.718901e+09          4         0.4977           0.4977
1282  NaN  1.718901e+09          4         0.5233           0.5233
1283  NaN  1.718901e+09          4         0.5233           0.5233
1284  NaN  1.718901e+09          4         0.5490           0.5490

      cpu_active_servers  bandwidth_utilization  bw_active_links  \
1                 0.0156                 0.1362           0.0333
2                 0.0467                 0.4085           0.0333
3                 0.0485                 0.4247           0.0333
4                 0.0797                 0.6970           0.0333
5                 0.0815                 0.7132           0.0333
...                  ...                    ...              ...
1280              0.2970                 0.6116           0.5600
1281              0.2970                 0.6116           0.5600
1282              0.3081                 0.6344           0.5600
1283              0.3081                 0.6344           0.5600
1284              0.3192                 0.6572           0.5600

      cache_utilization  cache_active_servers  ...       depart_time  \
1                0.4000                0.0103  ...    sfc_cache_p1_1
2                0.4000                0.0317  ...   sfc_unique_p1_1
3                0.4000                0.0333  ...    sfc_cache_p2_1
4                0.4000                0.0547  ...   sfc_unique_p2_1
5                0.4000                0.0564  ...    sfc_cache_p3_1
...                 ...                   ...  ...               ...
1280             0.6222                0.4147  ...  sfc_unique_p2_50
1281             0.6222                0.4147  ...   sfc_cache_p3_50
1282             0.6222                0.4361  ...  sfc_unique_p3_50
1283             0.6222                0.4361  ...   sfc_cache_p4_50
1284             0.6222                0.4575  ...  sfc_unique_p4_50

         sfc_id  cpu_saved  cache_saved  shared_vnfs  running_sfcs  \
1      0.000000        0.0            0            1             1
2      0.000000        0.0            1            2             1
3     10.333333       40.0            4            3             2
4     10.333333       40.0            5            4             2
5     20.666667       80.0            8            5             3
...         ...        ...          ...          ...           ...
1280  21.000000       40.0           16           28            18
1281  21.000000       40.0           16           28            18
1282  21.000000       40.0           16           29            19
1283  21.000000       40.0           16           29            19
1284  21.000000       40.0           17           30            20

      running_players running_sessions  server_crashed  trascode_bw
1                   1                0       32.333333            0
2                   1                0       64.666667            0
3                   1                0       32.333333            0
4                   1                0       64.666667            0
5                   1                0       32.333333            0
...               ...              ...             ...          ...
1280                6                0       64.666667           14
1281                6                0       32.333333           14
1282                6                0       64.666667           14
1283                6                0       32.333333           14
1284                6                0       64.666667           14

[1284 rows x 27 columns]
      No.          time  timestamp  number_of_sfc  cpu_utilization  \
1     NaN  1.718900e+09          4         0.0103           0.0617
2     NaN  1.718900e+09          4         0.0317           0.1900
3     NaN  1.718900e+09          4         0.0333           0.2000
4     NaN  1.718900e+09          4         0.0547           0.3283
5     NaN  1.718900e+09          4         0.0564           0.3383
...   ...           ...        ...            ...              ...
1271  NaN  1.718901e+09          4         0.4042           0.4042
1272  NaN  1.718901e+09          4         0.4061           0.4061
1273  NaN  1.718901e+09          4         0.4294           0.4294
1274  NaN  1.718901e+09          4         0.4312           0.4312
1275  NaN  1.718901e+09          4         0.4545           0.4545

      cpu_active_servers  bandwidth_utilization  bw_active_links  \
1                 0.0156                 0.1362           0.0333
2                 0.0467                 0.4085           0.0333
3                 0.0485                 0.4247           0.0333
4                 0.0797                 0.6970           0.0333
5                 0.0815                 0.7132           0.0333
...                  ...                    ...              ...
1271              0.2192                 0.5116           0.3636
1272              0.2211                 0.5159           0.3636
1273              0.2248                 0.5245           0.3636
1274              0.2266                 0.5288           0.3636
1275              0.2303                 0.5374           0.3636

      cache_utilization  cache_active_servers  ...       depart_time  \
1                   0.4                0.0103  ...    sfc_cache_p1_1
2                   0.4                0.0317  ...   sfc_unique_p1_1
3                   0.4                0.0333  ...    sfc_cache_p2_1
4                   0.4                0.0547  ...   sfc_unique_p2_1
5                   0.4                0.0564  ...    sfc_cache_p3_1
...                 ...                   ...  ...               ...
1271                0.5                0.3706  ...  sfc_unique_p2_50
1272                0.5                0.3722  ...   sfc_cache_p3_50
1273                0.5                0.3936  ...  sfc_unique_p3_50
1274                0.5                0.3953  ...   sfc_cache_p4_50
1275                0.5                0.4167  ...  sfc_unique_p4_50

         sfc_id  cpu_saved  cache_saved  shared_vnfs  running_sfcs  \
1      0.000000        0.0            0            1             1
2      0.000000        0.0            1            2             1
3     10.333333       40.0            4            3             2
4     10.333333       40.0            5            4             2
5     20.666667       80.0            8            5             3
...         ...        ...          ...          ...           ...
1271  36.000000      160.0           19           26            17
1272  46.333333      200.0           22           27            18
1273  46.333333      200.0           23           28            18
1274  56.666667      240.0           26           29            19
1275  56.666667      240.0           27           30            19

      running_players running_sessions  server_crashed  trascode_bw
1                   1                0       32.333333            0
2                   1                0       64.666667            0
3                   1                0       32.333333            0
4                   1                0       64.666667            0
5                   1                0       32.333333            0
...               ...              ...             ...          ...
1271                6                0       64.666667            2
1272                6                0       32.333333            2
1273                6                0       64.666667            2
1274                6                0       32.333333            2
1275                6                0       64.666667            2

[1275 rows x 27 columns]
      No.          time  timestamp  number_of_sfc  cpu_utilization  \
1     NaN  1.718900e+09          4         0.0103           0.0617
2     NaN  1.718900e+09          4         0.0317           0.1900
3     NaN  1.718900e+09          4         0.0333           0.2000
4     NaN  1.718900e+09          4         0.0547           0.3283
5     NaN  1.718900e+09          4         0.0564           0.3383
...   ...           ...        ...            ...              ...
1290  NaN  1.718901e+09          4         0.5812           0.5812
1291  NaN  1.718901e+09          4         0.5830           0.5830
1292  NaN  1.718901e+09          4         0.5830           0.5830
1293  NaN  1.718901e+09          4         0.5848           0.5848
1294  NaN  1.718901e+09          4         0.5736           0.5736

      cpu_active_servers  bandwidth_utilization  bw_active_links  \
1                 0.0156                 0.1362           0.0333
2                 0.0467                 0.4085           0.0333
3                 0.0485                 0.4247           0.0333
4                 0.0797                 0.6970           0.0333
5                 0.0815                 0.7132           0.0333
...                  ...                    ...              ...
1290              0.3135                 0.6455           0.6182
1291              0.3258                 0.6707           0.6182
1292              0.3258                 0.6707           0.6182
1293              0.3381                 0.6960           0.6182
1294              0.3194                 0.6575           0.5818

      cache_utilization  cache_active_servers  ...       depart_time  \
1                  0.40                0.0103  ...    sfc_cache_p1_1
2                  0.40                0.0317  ...   sfc_unique_p1_1
3                  0.40                0.0333  ...    sfc_cache_p2_1
4                  0.40                0.0547  ...   sfc_unique_p2_1
5                  0.40                0.0564  ...    sfc_cache_p3_1
...                 ...                   ...  ...               ...
1290               0.68                0.5328  ...  sfc_unique_p2_50
1291               0.68                0.5344  ...   sfc_cache_p3_50
1292               0.68                0.5344  ...  sfc_unique_p3_50
1293               0.68                0.5361  ...   sfc_cache_p4_50
1294               0.64                0.5258  ...  sfc_unique_p4_50

         sfc_id  cpu_saved  cache_saved  shared_vnfs  running_sfcs  \
1      0.000000        0.0            0            1             1
2      0.000000        0.0            1            2             1
3     10.333333       40.0            4            3             2
4     10.333333       40.0            5            4             2
5     20.666667       80.0            8            5             3
...         ...        ...          ...          ...           ...
1290  31.333333       80.0           24           36            21
1291  41.666667      120.0           27           37            22
1292  41.666667      120.0           27           37            22
1293  52.000000      160.0           29           38            23
1294  52.000000      160.0           29           37            22

      running_players running_sessions  server_crashed  trascode_bw
1                   1                0       32.333333            0
2                   1                0       64.666667            0
3                   1                0       32.333333            0
4                   1                0       64.666667            0
5                   1                0       32.333333            0
...               ...              ...             ...          ...
1290                6                0       64.666667            4
1291                6                0       32.333333            4
1292                6                0       64.666667            4
1293                6                0       32.333333            4
1294                6                0       64.666667            4

[1294 rows x 27 columns]
      No.          time  timestamp  number_of_sfc  cpu_utilization  \
1     NaN  1.718900e+09          4         0.0103           0.0617
2     NaN  1.718900e+09          4         0.0317           0.1900
3     NaN  1.718900e+09          4         0.0333           0.2000
4     NaN  1.718900e+09          4         0.0547           0.3283
5     NaN  1.718900e+09          4         0.0564           0.3383
...   ...           ...        ...            ...              ...
1277  NaN  1.718901e+09          4         0.5633           0.7243
1278  NaN  1.718901e+09          4         0.5715           0.7348
1279  NaN  1.718901e+09          4         0.6000           0.7714
1280  NaN  1.718901e+09          4         0.6022           0.7743
1281  NaN  1.718901e+09          4         0.5578           0.7171

      cpu_active_servers  bandwidth_utilization  bw_active_links  \
1                 0.0156                 0.1362           0.0333
2                 0.0467                 0.4085           0.0333
3                 0.0485                 0.4247           0.0333
4                 0.0797                 0.6970           0.0333
5                 0.0815                 0.7132           0.0333
...                  ...                    ...              ...
1277              0.2458                 0.5736           0.4444
1278              0.2541                 0.5929           0.4444
1279              0.2615                 0.6101           0.4444
1280              0.2652                 0.6188           0.4444
1281              0.3123                 0.7288           0.4000

      cache_utilization  cache_active_servers  ...       depart_time  \
1                0.4000                0.0103  ...    sfc_cache_p1_1
2                0.4000                0.0317  ...   sfc_unique_p1_1
3                0.4000                0.0333  ...    sfc_cache_p2_1
4                0.4000                0.0547  ...   sfc_unique_p2_1
5                0.4000                0.0564  ...    sfc_cache_p3_1
...                 ...                   ...  ...               ...
1277             0.5714                0.4225  ...  sfc_unique_p2_50
1278             0.5714                0.4286  ...   sfc_cache_p3_50
1279             0.5714                0.4500  ...  sfc_unique_p3_50
1280             0.5714                0.4517  ...   sfc_cache_p4_50
1281             0.5143                0.4183  ...  sfc_unique_p4_50

         sfc_id  cpu_saved  cache_saved  shared_vnfs  running_sfcs  \
1      0.000000        0.0            0            1             1
2      0.000000        0.0            1            2             1
3     10.333333       40.0            4            3             2
4     10.333333       40.0            5            4             2
5     20.666667       80.0            8            5             3
...         ...        ...          ...          ...           ...
1277  26.000000       80.0           14           27            19
1278  31.000000      120.0           16           28            20
1279  31.000000      120.0           17           29            20
1280  41.333333      160.0           20           30            21
1281  31.000000      120.0           16           27            19

      running_players running_sessions  server_crashed  trascode_bw
1                   1                0       32.333333            0
2                   1                0       64.666667            0
3                   1                0       32.333333            0
4                   1                0       64.666667            0
5                   1                0       32.333333            0

      No.          time  timestamp  number_of_sfc  cpu_utilization  \
1     NaN  1.718900e+09          4         0.0103           0.1233
2     NaN  1.718900e+09          4         0.0317           0.3800
3     NaN  1.718900e+09          4         0.0333           0.4000
4     NaN  1.718900e+09          4         0.0547           0.6567
5     NaN  1.718900e+09          4         0.0564           0.6767
...   ...           ...        ...            ...              ...
1653  NaN  1.718901e+09          4         0.5852           0.7152
1654  NaN  1.718901e+09          4         0.5964           0.6560
1655  NaN  1.718901e+09          4         0.6197           0.6817
1656  NaN  1.718901e+09          4         0.6215           0.6837
1657  NaN  1.718901e+09          4         0.6448           0.7093

      cpu_active_servers  bandwidth_utilization  bw_active_links  \
1                 0.0018                 0.0647           0.0333
2                 0.0055                 0.1940           0.0333
3                 0.0074                 0.2587           0.0333
4                 0.0111                 0.3880           0.0333
5                 0.0129                 0.4527           0.0333
...                  ...                    ...              ...
1653              0.1356                 0.3954           0.4727
1654              0.1374                 0.3699           0.5091
1655              0.1411                 0.3799           0.5091
1656              0.1430                 0.3849           0.5091
1657              0.1466                 0.3948           0.5091

      cache_utilization  cache_active_servers  ...       depart_time  \
1                0.4000                0.0103  ...    sfc_cache_p1_1
2                0.4000                0.0317  ...   sfc_unique_p1_1
3                0.4000                0.0333  ...    sfc_cache_p2_1
4                0.4000                0.0547  ...   sfc_unique_p2_1
5                0.4000                0.0564  ...    sfc_cache_p3_1
...                 ...                   ...  ...               ...
1653             0.5778                0.5364  ...  sfc_unique_p2_50
1654             0.5600                0.5467  ...   sfc_cache_p3_50
1655             0.5600                0.5681  ...  sfc_unique_p3_50
1656             0.5600                0.5697  ...   sfc_cache_p4_50
1657             0.5600                0.5911  ...  sfc_unique_p4_50

         sfc_id  cpu_saved  cache_saved  shared_vnfs  running_sfcs  \
1      0.000000        0.0            0            1             1
2      0.000000        0.0            1            2             1
3     10.333333       40.0            4            3             2
4     10.333333       40.0            5            4             2
5     20.666667       80.0            8            5             3
...         ...        ...          ...          ...           ...
1653  77.333333      320.0           36           39            21
1654  77.333333      320.0           36           40            22
1655  77.333333      320.0           37           41            22
1656  87.666667      360.0           40           42            23
1657  87.666667      360.0           41           43            23

      running_players running_sessions  server_crashed  trascode_bw
1                   1                0       32.333333            0
2                   1                0       64.666667            0
3                   1                0       32.333333            0
4                   1                0       64.666667            0
5                   1                0       32.333333            0
...               ...              ...             ...          ...
1653                6                0       64.666667            4
1654                6                0       32.333333            4
1655                6                0       64.666667            4
1656                6                0       32.333333            4
1657                6                0       64.666667            4

[1657 rows x 27 columns]
      No.          time  timestamp  number_of_sfc  cpu_utilization  \
1     NaN  1.718900e+09          4         0.0103           0.1233
2     NaN  1.718900e+09          4         0.0317           0.3800
3     NaN  1.718900e+09          4         0.0333           0.4000
4     NaN  1.718900e+09          4         0.0547           0.6567
5     NaN  1.718900e+09          4         0.0564           0.6767
...   ...           ...        ...            ...              ...
1552  NaN  1.718901e+09          4         0.6085           0.7437
1553  NaN  1.718901e+09          4         0.6103           0.7459
1554  NaN  1.718901e+09          4         0.6336           0.7744
1555  NaN  1.718901e+09          4         0.6355           0.7767
1556  NaN  1.718901e+09          4         0.6588           0.8052

      cpu_active_servers  bandwidth_utilization  bw_active_links  \
1                 0.0018                 0.0647           0.0333
2                 0.0055                 0.1940           0.0333
3                 0.0074                 0.2587           0.0333
4                 0.0111                 0.3880           0.0333
5                 0.0129                 0.4527           0.0333
...                  ...                    ...              ...
1552              0.2028                 0.5069           0.4727
1553              0.2065                 0.5161           0.4727
1554              0.2138                 0.5346           0.4727
1555              0.2175                 0.5439           0.4727
1556              0.2432                 0.6080           0.4727

      cache_utilization  cache_active_servers  ...       depart_time  \
1                0.4000                0.0103  ...    sfc_cache_p1_1
2                0.4000                0.0317  ...   sfc_unique_p1_1
3                0.4000                0.0333  ...    sfc_cache_p2_1
4                0.4000                0.0547  ...   sfc_unique_p2_1
5                0.4000                0.0564  ...    sfc_cache_p3_1
...                 ...                   ...  ...               ...
1552             0.5778                0.5578  ...  sfc_unique_p2_50
1553             0.5778                0.5594  ...   sfc_cache_p3_50
1554             0.5778                0.5808  ...  sfc_unique_p3_50
1555             0.5778                0.5825  ...   sfc_cache_p4_50
1556             0.5778                0.6039  ...  sfc_unique_p4_50

         sfc_id  cpu_saved  cache_saved  shared_vnfs  running_sfcs  \
1      0.000000        0.0            0            1             1
2      0.000000        0.0            1            2             1
3     10.333333       40.0            4            3             2
4     10.333333       40.0            5            4             2
5     20.666667       80.0            8            5             3
...         ...        ...          ...          ...           ...
1552  77.333333      320.0           41           40            22
1553  87.666667      360.0           44           41            23
1554  87.666667      360.0           45           42            23
1555  98.000000      400.0           48           43            24
1556  98.000000      400.0           48           44            24

      running_players running_sessions  server_crashed  trascode_bw
1                   1                0       32.333333            0
2                   1                0       64.666667            0
3                   1                0       32.333333            0
4                   1                0       64.666667            0
5                   1                0       32.333333            0
...               ...              ...             ...          ...
1552                6                0       64.666667            6
1553                6                0       32.333333            6
1554                6                0       64.666667            6
1555                6                0       32.333333            6
1556                6                0       64.666667            6

[1556 rows x 27 columns]
      No.          time  timestamp  number_of_sfc  cpu_utilization  \
1     NaN  1.718900e+09          4         0.0103           0.1233
2     NaN  1.718900e+09          4         0.0317           0.3800
3     NaN  1.718900e+09          4         0.0333           0.4000
4     NaN  1.718900e+09          4         0.0547           0.6567
5     NaN  1.718900e+09          4         0.0564           0.6767
...   ...           ...        ...            ...              ...
1559  NaN  1.718901e+09          4         0.7389           0.8313
1560  NaN  1.718901e+09          4         0.7411           0.8337
1561  NaN  1.718901e+09          4         0.7696           0.8658
1562  NaN  1.718901e+09          4         0.7719           0.8683
1563  NaN  1.718901e+09          4         0.8004           0.8004

      cpu_active_servers  bandwidth_utilization  bw_active_links  \
1                 0.0018                 0.0647           0.0333
2                 0.0055                 0.1940           0.0333
3                 0.0074                 0.2587           0.0333
4                 0.0111                 0.3880           0.0333
5                 0.0129                 0.4527           0.0333
...                  ...                    ...              ...
1559              0.2688                 0.5534           0.6222
1560              0.2706                 0.5572           0.6222
1561              0.2743                 0.5648           0.6222
1562              0.2762                 0.5686           0.6222
1563              0.2890                 0.5620           0.6222

      cache_utilization  cache_active_servers  ...       depart_time  \
1                   0.4                0.0103  ...    sfc_cache_p1_1
2                   0.4                0.0317  ...   sfc_unique_p1_1
3                   0.4                0.0333  ...    sfc_cache_p2_1
4                   0.4                0.0547  ...   sfc_unique_p2_1
5                   0.4                0.0564  ...    sfc_cache_p3_1
...                 ...                   ...  ...               ...
1559                0.8                0.5542  ...  sfc_unique_p2_50
1560                0.8                0.5558  ...   sfc_cache_p3_50
1561                0.8                0.5772  ...  sfc_unique_p3_50
1562                0.8                0.5789  ...   sfc_cache_p4_50
1563                0.8                0.6003  ...  sfc_unique_p4_50

         sfc_id  cpu_saved  cache_saved  shared_vnfs  running_sfcs  \
1      0.000000        0.0            0            1             1
2      0.000000        0.0            1            2             1
3     10.333333       40.0            4            3             2
4     10.333333       40.0            5            4             2
5     20.666667       80.0            8            5             3
...         ...        ...          ...          ...           ...
1559  57.000000      200.0           31           38            21
1560  67.333333      240.0           34           39            22
1561  67.333333      240.0           35           40            22
1562  77.666667      280.0           38           41            23
1563  77.666667      280.0           38           42            23

      running_players running_sessions  server_crashed  trascode_bw
1                   1                0       32.333333            0
2                   1                0       64.666667            0
3                   1                0       32.333333            0
4                   1                0       64.666667            0
5                   1                0       32.333333            0
...               ...              ...             ...          ...
1559                6                0       64.666667           18
1560                6                0       32.333333           18
1561                6                0       64.666667           18
1562                6                0       32.333333           18
1563                6                0       64.666667           18

[1563 rows x 27 columns]
      No.          time  timestamp  number_of_sfc  cpu_utilization  \
1     NaN  1.718900e+09          4         0.0103           0.1233
2     NaN  1.718900e+09          4         0.0317           0.3800
3     NaN  1.718900e+09          4         0.0333           0.4000
4     NaN  1.718900e+09          4         0.0547           0.6567
5     NaN  1.718900e+09          4         0.0564           0.6767
...   ...           ...        ...            ...              ...
1555  NaN  1.718901e+09          4         0.6019           0.8026
1556  NaN  1.718901e+09          4         0.6036           0.8048
1557  NaN  1.718901e+09          4         0.6250           0.7500
1558  NaN  1.718901e+09          4         0.6267           0.7520
1559  NaN  1.718901e+09          4         0.6481           0.7777

      cpu_active_servers  bandwidth_utilization  bw_active_links  \
1                 0.0018                 0.0647           0.0333
2                 0.0055                 0.1940           0.0333
3                 0.0074                 0.2587           0.0333
4                 0.0111                 0.3880           0.0333
5                 0.0129                 0.4527           0.0333
...                  ...                    ...              ...
1555              0.1603                 0.5609           0.3667
1556              0.1640                 0.5739           0.3667
1557              0.1805                 0.5743           0.3667
1558              0.1842                 0.5861           0.3667
1559              0.1916                 0.6096           0.3667

      cache_utilization  cache_active_servers  ...       depart_time  \
1                0.4000                0.0103  ...    sfc_cache_p1_1
2                0.4000                0.0317  ...   sfc_unique_p1_1
3                0.4000                0.0333  ...    sfc_cache_p2_1
4                0.4000                0.0547  ...   sfc_unique_p2_1
5                0.4000                0.0564  ...    sfc_cache_p3_1
...                 ...                   ...  ...               ...
1555             0.4889                0.6019  ...  sfc_unique_p2_50
1556             0.4889                0.6036  ...   sfc_cache_p3_50
1557             0.4889                0.6250  ...  sfc_unique_p3_50
1558             0.4889                0.6267  ...   sfc_cache_p4_50
1559             0.4889                0.6481  ...  sfc_unique_p4_50

          sfc_id  cpu_saved  cache_saved  shared_vnfs  running_sfcs  \
1       0.000000        0.0            0            1             1
2       0.000000        0.0            1            2             1
3      10.333333       40.0            4            3             2
4      10.333333       40.0            5            4             2
5      20.666667       80.0            8            5             3
...          ...        ...          ...          ...           ...
1555  113.666667      440.0           52           44            22
1556  124.000000      480.0           55           45            23
1557  124.000000      480.0           55           46            23
1558  134.333333      520.0           58           47            24
1559  134.333333      520.0           58           48            24

      running_players running_sessions  server_crashed  trascode_bw
1                   1                0       32.333333            0
2                   1                0       64.666667            0
3                   1                0       32.333333            0
4                   1                0       64.666667            0
5                   1                0       32.333333            0
...               ...              ...             ...          ...
1555                6                0       64.666667            0
1556                6                0       32.333333            0
1557                6                0       64.666667            0
1558                6                0       32.333333            0
1559                6                0       64.666667            0

[1559 rows x 27 columns]
      No.          time  timestamp  number_of_sfc  cpu_utilization  \
1     NaN  1.718900e+09          4         0.0103           0.1233
2     NaN  1.718900e+09          4         0.0317           0.3800
3     NaN  1.718900e+09          4         0.0333           0.4000
4     NaN  1.718900e+09          4         0.0547           0.6567
5     NaN  1.718900e+09          4         0.0564           0.6767
...   ...           ...        ...            ...              ...
1576  NaN  1.718901e+09          4         0.5475           0.7300
1577  NaN  1.718901e+09          4         0.5492           0.7322
1578  NaN  1.718901e+09          4         0.5706           0.7607
1579  NaN  1.718901e+09          4         0.5722           0.7630
1580  NaN  1.718901e+09          4         0.5936           0.7123

      cpu_active_servers  bandwidth_utilization  bw_active_links  \
1                 0.0018                 0.0647           0.0333
2                 0.0055                 0.1940           0.0333
3                 0.0074                 0.2587           0.0333
4                 0.0111                 0.3880           0.0333
5                 0.0129                 0.4527           0.0333
...                  ...                    ...              ...
1576              0.0802                 0.4011           0.4000
1577              0.0802                 0.4011           0.4000
1578              0.0802                 0.4011           0.4000
1579              0.0802                 0.4011           0.4000
1580              0.0894                 0.3910           0.4000

      cache_utilization  cache_active_servers  ...       depart_time  \
1                0.4000                0.0103  ...    sfc_cache_p1_1
2                0.4000                0.0317  ...   sfc_unique_p1_1
3                0.4000                0.0333  ...    sfc_cache_p2_1
4                0.4000                0.0547  ...   sfc_unique_p2_1
5                0.4000                0.0564  ...    sfc_cache_p3_1
...                 ...                   ...  ...               ...
1576             0.5333                0.5475  ...  sfc_unique_p2_50
1577             0.5333                0.5492  ...   sfc_cache_p3_50
1578             0.5333                0.5706  ...  sfc_unique_p3_50
1579             0.5333                0.5722  ...   sfc_cache_p4_50
1580             0.5333                0.5936  ...  sfc_unique_p4_50

         sfc_id  cpu_saved  cache_saved  shared_vnfs  running_sfcs  \
1      0.000000        0.0            0            1             1
2      0.000000        0.0            1            2             1
3     10.333333       40.0            4            3             2
4     10.333333       40.0            5            4             2
5     20.666667       80.0            8            5             3
...         ...        ...          ...          ...           ...
1576  77.333333      320.0           43           39            20
1577  87.666667      360.0           46           40            21
1578  87.666667      360.0           47           41            21
1579  98.000000      400.0           50           42            22
1580  98.000000      400.0           50           43            22

      running_players running_sessions  server_crashed  trascode_bw
1                   1                0       32.333333            0
2                   1                0       64.666667            0
3                   1                0       32.333333            0
4                   1                0       64.666667            0
5                   1                0       32.333333            0

      No.          time  timestamp  number_of_sfc  cpu_utilization  \
1     NaN  1.718900e+09          4         0.0103           0.1233
2     NaN  1.718900e+09          4         0.0317           0.3800
3     NaN  1.718900e+09          4         0.0333           0.4000
4     NaN  1.718900e+09          4         0.0547           0.6567
5     NaN  1.718900e+09          4         0.0564           0.6767
...   ...           ...        ...            ...              ...
1488  NaN  1.718901e+09          4         0.5437           0.6117
1489  NaN  1.718901e+09          4         0.5574           0.5574
1490  NaN  1.718901e+09          4         0.5859           0.5859
1491  NaN  1.718901e+09          4         0.5881           0.5881
1492  NaN  1.718901e+09          4         0.6167           0.6167

      cpu_active_servers  bandwidth_utilization  bw_active_links  \
1                 0.0018                 0.0647           0.0333
2                 0.0055                 0.1940           0.0333
3                 0.0074                 0.2587           0.0333
4                 0.0111                 0.3880           0.0333
5                 0.0129                 0.4527           0.0333
...                  ...                    ...              ...
1488              0.1472                 0.3964           0.4444
1489              0.1509                 0.3773           0.4889
1490              0.1583                 0.3958           0.4889
1491              0.1620                 0.4050           0.4889
1492              0.1694                 0.4235           0.4889

      cache_utilization  cache_active_servers  ...       depart_time  \
1                0.4000                0.0103  ...    sfc_cache_p1_1
2                0.4000                0.0317  ...   sfc_unique_p1_1
3                0.4000                0.0333  ...    sfc_cache_p2_1
4                0.4000                0.0547  ...   sfc_unique_p2_1
5                0.4000                0.0564  ...    sfc_cache_p3_1
...                 ...                   ...  ...               ...
1488             0.5000                0.4078  ...  sfc_unique_p2_50
1489             0.4889                0.4181  ...   sfc_cache_p3_50
1490             0.4889                0.4394  ...  sfc_unique_p3_50
1491             0.4889                0.4411  ...   sfc_cache_p4_50
1492             0.4889                0.4625  ...  sfc_unique_p4_50

         sfc_id  cpu_saved  cache_saved  shared_vnfs  running_sfcs  \
1      0.000000        0.0            0            1             1
2      0.000000        0.0            1            2             1
3     10.333333       40.0            4            3             2
4     10.333333       40.0            5            4             2
5     20.666667       80.0            8            5             3
...         ...        ...          ...          ...           ...
1488  67.333333      240.0           31           30            19
1489  67.333333      240.0           31           31            20
1490  67.333333      240.0           32           32            20
1491  77.666667      280.0           35           33            21
1492  77.666667      280.0           36           34            21

      running_players running_sessions  server_crashed  trascode_bw
1                   1                0       32.333333            0
2                   1                0       64.666667            0
3                   1                0       32.333333            0
4                   1                0       64.666667            0
5                   1                0       32.333333            0
...               ...              ...             ...          ...
1488                6                0       64.666667           10
1489                6                0       32.333333           10
1490                6                0       64.666667           10
1491                6                0       32.333333           10
1492                6                0       64.666667           10

[1492 rows x 27 columns]
      No.          time  timestamp  number_of_sfc  cpu_utilization  \
1     NaN  1.718900e+09          4         0.0103           0.1233
2     NaN  1.718900e+09          4         0.0317           0.3800
3     NaN  1.718900e+09          4         0.0333           0.4000
4     NaN  1.718900e+09          4         0.0547           0.6567
5     NaN  1.718900e+09          4         0.0564           0.6767
...   ...           ...        ...            ...              ...
1672  NaN  1.718901e+09          4         0.5993           0.6659
1673  NaN  1.718901e+09          4         0.6013           0.6681
1674  NaN  1.718901e+09          4         0.6270           0.6270
1675  NaN  1.718901e+09          4         0.6290           0.6290
1676  NaN  1.718901e+09          4         0.6547           0.6547

      cpu_active_servers  bandwidth_utilization  bw_active_links  \
1                 0.0018                 0.0647           0.0333
2                 0.0055                 0.1940           0.0333
3                 0.0074                 0.2587           0.0333
4                 0.0111                 0.3880           0.0333
5                 0.0129                 0.4527           0.0333
...                  ...                    ...              ...
1672              0.1935                 0.4516           0.4400
1673              0.1935                 0.4516           0.4400
1674              0.2027                 0.4433           0.4400
1675              0.2027                 0.4433           0.4400
1676              0.2118                 0.4633           0.4400

      cache_utilization  cache_active_servers  ...       depart_time  \
1                0.4000                0.0103  ...    sfc_cache_p1_1
2                0.4000                0.0317  ...   sfc_unique_p1_1
3                0.4000                0.0333  ...    sfc_cache_p2_1
4                0.4000                0.0547  ...   sfc_unique_p2_1
5                0.4000                0.0564  ...    sfc_cache_p3_1
...                 ...                   ...  ...               ...
1672             0.6286                0.4994  ...  sfc_unique_p2_50
1673             0.6286                0.5011  ...   sfc_cache_p3_50
1674             0.6286                0.5225  ...  sfc_unique_p3_50
1675             0.6286                0.5242  ...   sfc_cache_p4_50
1676             0.6286                0.5456  ...  sfc_unique_p4_50

          sfc_id  cpu_saved  cache_saved  shared_vnfs  running_sfcs  \
1       0.000000        0.0            0            1             1
2       0.000000        0.0            1            2             1
3      10.333333       40.0            4            3             2
4      10.333333       40.0            5            4             2
5      20.666667       80.0            8            5             3
...          ...        ...          ...          ...           ...
1672  108.333333      440.0           45           39            22
1673  118.666667      480.0           48           40            23
1674  118.666667      480.0           48           41            23
1675  129.000000      520.0           51           42            24
1676  129.000000      520.0           52           43            24

      running_players running_sessions  server_crashed  trascode_bw
1                   1                0       32.333333            0
2                   1                0       64.666667            0
3                   1                0       32.333333            0
4                   1                0       64.666667            0
5                   1                0       32.333333            0
...               ...              ...             ...          ...
1672                6                0       64.666667            7
1673                6                0       32.333333            7
1674                6                0       64.666667            7
1675                6                0       32.333333            7
1676                6                0       64.666667            7

[1676 rows x 27 columns]
      No.          time  timestamp  number_of_sfc  cpu_utilization  \
1     NaN  1.718900e+09          4         0.0103           0.1233
2     NaN  1.718900e+09          4         0.0317           0.3800
3     NaN  1.718900e+09          4         0.0333           0.4000
4     NaN  1.718900e+09          4         0.0547           0.6567
5     NaN  1.718900e+09          4         0.0564           0.6767
...   ...           ...        ...            ...              ...
1440  NaN  1.718901e+09          4         0.5556           0.7143
1441  NaN  1.718901e+09          4         0.5578           0.7171
1442  NaN  1.718901e+09          4         0.5863           0.7538
1443  NaN  1.718901e+09          4         0.6000           0.7714
1444  NaN  1.718901e+09          4         0.6000           0.7714

      cpu_active_servers  bandwidth_utilization  bw_active_links  \
1                 0.0018                 0.0647           0.0333
2                 0.0055                 0.1940           0.0333
3                 0.0074                 0.2587           0.0333
4                 0.0111                 0.3880           0.0333
5                 0.0129                 0.4527           0.0333
...                  ...                    ...              ...
1440              0.1883                 0.5491           0.4444
1441              0.1920                 0.5599           0.4444
1442              0.1994                 0.5814           0.4444
1443              0.2140                 0.6243           0.4889
1444              0.2140                 0.6243           0.4889

      cache_utilization  cache_active_servers  ...       depart_time  \
1                0.4000                0.0103  ...    sfc_cache_p1_1
2                0.4000                0.0317  ...   sfc_unique_p1_1
3                0.4000                0.0333  ...    sfc_cache_p2_1
4                0.4000                0.0547  ...   sfc_unique_p2_1
5                0.4000                0.0564  ...    sfc_cache_p3_1
...                 ...                   ...  ...               ...
1440             0.6667                0.4167  ...  sfc_unique_p2_50
1441             0.6667                0.4183  ...   sfc_cache_p3_50
1442             0.6667                0.4397  ...  sfc_unique_p3_50
1443             0.7333                0.4500  ...   sfc_cache_p4_50
1444             0.7333                0.4500  ...  sfc_unique_p4_50

         sfc_id  cpu_saved  cache_saved  shared_vnfs  running_sfcs  \
1      0.000000        0.0            0            1             1
2      0.000000        0.0            1            2             1
3     10.333333       40.0            4            3             2
4     10.333333       40.0            5            4             2
5     20.666667       80.0            8            5             3
...         ...        ...          ...          ...           ...
1440  56.666667      240.0           29           30            16
1441  67.000000      280.0           32           31            17
1442  67.000000      280.0           33           32            17
1443  67.000000      280.0           33           33            18
1444  67.000000      280.0           33           33            18

      running_players running_sessions  server_crashed  trascode_bw
1                   1                0       32.333333            0
2                   1                0       64.666667            0
3                   1                0       32.333333            0
4                   1                0       64.666667            0
5                   1                0       32.333333            0
...               ...              ...             ...          ...
1440                5                0       64.666667            9
1441                5                0       32.333333            9
1442                5                0       64.666667            9
1443                5                0       30.716667            9
1444                5                0       48.500000            9

[1444 rows x 27 columns]
      No.          time  timestamp  number_of_sfc  cpu_utilization  \
1     NaN  1.718900e+09          4         0.0103           0.1233
2     NaN  1.718900e+09          4         0.0317           0.3800
3     NaN  1.718900e+09          4         0.0333           0.4000
4     NaN  1.718900e+09          4         0.0547           0.6567
5     NaN  1.718900e+09          4         0.0564           0.6767
...   ...           ...        ...            ...              ...
1548  NaN  1.718901e+09          4         0.6437           0.7152
1549  NaN  1.718901e+09          4         0.6457           0.7174
1550  NaN  1.718901e+09          4         0.6713           0.7459
1551  NaN  1.718901e+09          4         0.6733           0.7481
1552  NaN  1.718901e+09          4         0.6990           0.7767

      cpu_active_servers  bandwidth_utilization  bw_active_links  \
1                 0.0018                 0.0647           0.0333
2                 0.0055                 0.1940           0.0333
3                 0.0074                 0.2587           0.0333
4                 0.0111                 0.3880           0.0333
5                 0.0129                 0.4527           0.0333
...                  ...                    ...              ...
1548              0.1327                 0.3574           0.5200
1549              0.1346                 0.3624           0.5200
1550              0.1383                 0.3723           0.5200
1551              0.1401                 0.3773           0.5200
1552              0.1713                 0.4611           0.5200

      cache_utilization  cache_active_servers  ...       depart_time  \
1                0.4000                0.0103  ...    sfc_cache_p1_1
2                0.4000                0.0317  ...   sfc_unique_p1_1
3                0.4000                0.0333  ...    sfc_cache_p2_1
4                0.4000                0.0547  ...   sfc_unique_p2_1
5                0.4000                0.0564  ...    sfc_cache_p3_1
...                 ...                   ...  ...               ...
1548             0.5778                0.5364  ...  sfc_unique_p2_50
1549             0.5778                0.5381  ...   sfc_cache_p3_50
1550             0.5778                0.5594  ...  sfc_unique_p3_50
1551             0.5778                0.5611  ...   sfc_cache_p4_50
1552             0.5778                0.5825  ...  sfc_unique_p4_50

         sfc_id  cpu_saved  cache_saved  shared_vnfs  running_sfcs  \
1      0.000000        0.0            0            1             1
2      0.000000        0.0            1            2             1
3     10.333333       40.0            4            3             2
4     10.333333       40.0            5            4             2
5     20.666667       80.0            8            5             3
...         ...        ...          ...          ...           ...
1548  77.333333      320.0           40           39            21
1549  87.666667      360.0           43           40            22
1550  87.666667      360.0           44           41            22
1551  98.000000      400.0           47           42            23
1552  98.000000      400.0           47           43            23

      running_players running_sessions  server_crashed  trascode_bw
1                   1                0       32.333333            0
2                   1                0       64.666667            0
3                   1                0       32.333333            0
4                   1                0       64.666667            0
5                   1                0       32.333333            0
...               ...              ...             ...          ...
1548                6                0       64.666667            6
1549                6                0       32.333333            6
1550                6                0       64.666667            6
1551                6                0       32.333333            6
1552                6                0       64.666667            6

[1552 rows x 27 columns]
      No.          time  timestamp  number_of_sfc  cpu_utilization  \
1     NaN  1.718900e+09          4         0.0103           0.1233
2     NaN  1.718900e+09          4         0.0317           0.3800
3     NaN  1.718900e+09          4         0.0333           0.4000
4     NaN  1.718900e+09          4         0.0547           0.6567
5     NaN  1.718900e+09          4         0.0564           0.6767
...   ...           ...        ...            ...              ...
1455  NaN  1.718901e+09          4         0.5307           0.6633
1456  NaN  1.718901e+09          4         0.5327           0.6658
1457  NaN  1.718901e+09          4         0.5583           0.6979
1458  NaN  1.718901e+09          4         0.5603           0.7004
1459  NaN  1.718901e+09          4         0.5860           0.7325

      cpu_active_servers  bandwidth_utilization  bw_active_links  \
1                 0.0018                 0.0647           0.0333
2                 0.0055                 0.1940           0.0333
3                 0.0074                 0.2587           0.0333
4                 0.0111                 0.3880           0.0333
5                 0.0129                 0.4527           0.0333
...                  ...                    ...              ...
1455              0.1237                 0.3936           0.4400
1456              0.1255                 0.3995           0.4400
1457              0.1292                 0.4112           0.4400
1458              0.1311                 0.4171           0.4400
1459              0.1348                 0.4288           0.4400

      cache_utilization  cache_active_servers  ...       depart_time  \
1                0.4000                0.0103  ...    sfc_cache_p1_1
2                0.4000                0.0317  ...   sfc_unique_p1_1
3                0.4000                0.0333  ...    sfc_cache_p2_1
4                0.4000                0.0547  ...   sfc_unique_p2_1
5                0.4000                0.0564  ...    sfc_cache_p3_1
...                 ...                   ...  ...               ...
1455             0.6286                0.4422  ...  sfc_unique_p2_50
1456             0.6286                0.4439  ...   sfc_cache_p3_50
1457             0.6286                0.4653  ...  sfc_unique_p3_50
1458             0.6286                0.4669  ...   sfc_cache_p4_50
1459             0.6286                0.4883  ...  sfc_unique_p4_50

         sfc_id  cpu_saved  cache_saved  shared_vnfs  running_sfcs  \
1      0.000000        0.0            0            1             1
2      0.000000        0.0            1            2             1
3     10.333333       40.0            4            3             2
4     10.333333       40.0            5            4             2
5     20.666667       80.0            8            5             3
...         ...        ...          ...          ...           ...
1455  51.666667      200.0           29           31            16
1456  62.000000      240.0           32           32            17
1457  62.000000      240.0           33           33            17
1458  72.333333      280.0           36           34            18
1459  72.333333      280.0           37           35            18

      running_players running_sessions  server_crashed  trascode_bw
1                   1                0       32.333333            0
2                   1                0       64.666667            0
3                   1                0       32.333333            0
4                   1                0       64.666667            0
5                   1                0       32.333333            0

      No.          time  timestamp  number_of_sfc  cpu_utilization  \
1     NaN  1.718900e+09          4         0.0103           0.0617
2     NaN  1.718900e+09          4         0.0317           0.1900
3     NaN  1.718900e+09          4         0.0333           0.2000
4     NaN  1.718900e+09          4         0.0547           0.3283
5     NaN  1.718900e+09          4         0.0564           0.3383
...   ...           ...        ...            ...              ...
1377  NaN  1.718901e+09          4         0.4097           0.4097
1378  NaN  1.718901e+09          4         0.4117           0.4117
1379  NaN  1.718901e+09          4         0.4373           0.4373
1380  NaN  1.718901e+09          4         0.4393           0.4393
1381  NaN  1.718901e+09          4         0.4650           0.4650

      cpu_active_servers  bandwidth_utilization  bw_active_links  \
1                 0.0156                 0.1362           0.0333
2                 0.0467                 0.4085           0.0333
3                 0.0485                 0.4247           0.0333
4                 0.0797                 0.6970           0.0333
5                 0.0815                 0.7132           0.0333
...                  ...                    ...              ...
1377              0.1834                 0.4584           0.4400
1378              0.1852                 0.4630           0.4400
1379              0.1889                 0.4723           0.4400
1380              0.1908                 0.4769           0.4400
1381              0.2036                 0.4751           0.4400

      cache_utilization  cache_active_servers  ...       depart_time  \
1                  0.40                0.0103  ...    sfc_cache_p1_1
2                  0.40                0.0317  ...   sfc_unique_p1_1
3                  0.40                0.0333  ...    sfc_cache_p2_1
4                  0.40                0.0547  ...   sfc_unique_p2_1
5                  0.40                0.0564  ...    sfc_cache_p3_1
...                 ...                   ...  ...               ...
1377               0.55                0.3414  ...  sfc_unique_p2_50
1378               0.55                0.3431  ...   sfc_cache_p3_50
1379               0.55                0.3644  ...  sfc_unique_p3_50
1380               0.55                0.3661  ...   sfc_cache_p4_50
1381               0.55                0.3875  ...  sfc_unique_p4_50

         sfc_id  cpu_saved  cache_saved  shared_vnfs  running_sfcs  \
1      0.000000        0.0            0            1             1
2      0.000000        0.0            1            2             1
3     10.333333       40.0            4            3             2
4     10.333333       40.0            5            4             2
5     20.666667       80.0            8            5             3
...         ...        ...          ...          ...           ...
1377  56.666667      240.0           26           27            17
1378  67.000000      280.0           29           28            18
1379  67.000000      280.0           30           29            18
1380  77.333333      320.0           33           30            19
1381  77.333333      320.0           33           31            19

      running_players running_sessions  server_crashed  trascode_bw
1                   1                0       32.333333            0
2                   1                0       64.666667            0
3                   1                0       32.333333            0
4                   1                0       64.666667            0
5                   1                0       32.333333            0
...               ...              ...             ...          ...
1377                6                0       64.666667            3
1378                6                0       32.333333            3
1379                6                0       64.666667            3
1380                6                0       32.333333            3
1381                6                0       64.666667            3

[1381 rows x 27 columns]
      No.          time  timestamp  number_of_sfc  cpu_utilization  \
1     NaN  1.718900e+09          4         0.0103           0.0617
2     NaN  1.718900e+09          4         0.0317           0.1900
3     NaN  1.718900e+09          4         0.0333           0.2000
4     NaN  1.718900e+09          4         0.0547           0.3283
5     NaN  1.718900e+09          4         0.0564           0.3383
...   ...           ...        ...            ...              ...
1363  NaN  1.718901e+09          4         0.4824           0.6633
1364  NaN  1.718901e+09          4         0.4842           0.6658
1365  NaN  1.718901e+09          4         0.5076           0.6979
1366  NaN  1.718901e+09          4         0.5094           0.7004
1367  NaN  1.718901e+09          4         0.5327           0.6511

      cpu_active_servers  bandwidth_utilization  bw_active_links  \
1                 0.0156                 0.1362           0.0333
2                 0.0467                 0.4085           0.0333
3                 0.0485                 0.4247           0.0333
4                 0.0797                 0.6970           0.0333
5                 0.0815                 0.7132           0.0333
...                  ...                    ...              ...
1363              0.2171                 0.6908           0.2909
1364              0.2190                 0.6967           0.2909
1365              0.2227                 0.7085           0.2909
1366              0.2245                 0.7144           0.2909
1367              0.2319                 0.7379           0.2909

      cache_utilization  cache_active_servers  ...       depart_time  \
1                0.4000                0.0103  ...    sfc_cache_p1_1
2                0.4000                0.0317  ...   sfc_unique_p1_1
3                0.4000                0.0333  ...    sfc_cache_p2_1
4                0.4000                0.0547  ...   sfc_unique_p2_1
5                0.4000                0.0564  ...    sfc_cache_p3_1
...                 ...                   ...  ...               ...
1363             0.4571                0.4422  ...  sfc_unique_p2_50
1364             0.4571                0.4439  ...   sfc_cache_p3_50
1365             0.4571                0.4653  ...  sfc_unique_p3_50
1366             0.4571                0.4669  ...   sfc_cache_p4_50
1367             0.4571                0.4883  ...  sfc_unique_p4_50

         sfc_id  cpu_saved  cache_saved  shared_vnfs  running_sfcs  \
1      0.000000        0.0            0            1             1
2      0.000000        0.0            1            2             1
3     10.333333       40.0            4            3             2
4     10.333333       40.0            5            4             2
5     20.666667       80.0            8            5             3
...         ...        ...          ...          ...           ...
1363  77.333333      320.0           37           32            16
1364  87.666667      360.0           40           33            17
1365  87.666667      360.0           40           34            17
1366  98.000000      400.0           43           35            18
1367  98.000000      400.0           43           36            18

      running_players running_sessions  server_crashed  trascode_bw
1                   1                0       32.333333            0
2                   1                0       64.666667            0
3                   1                0       32.333333            0
4                   1                0       64.666667            0
5                   1                0       32.333333            0
...               ...              ...             ...          ...
1363                5                0       64.666667            3
1364                5                0       32.333333            3
1365                5                0       64.666667            3
1366                5                0       32.333333            3
1367                5                0       64.666667            3

[1367 rows x 27 columns]
      No.          time  timestamp  number_of_sfc  cpu_utilization  \
1     NaN  1.718900e+09          4         0.0103           0.0617
2     NaN  1.718900e+09          4         0.0317           0.1900
3     NaN  1.718900e+09          4         0.0333           0.2000
4     NaN  1.718900e+09          4         0.0547           0.3283
5     NaN  1.718900e+09          4         0.0564           0.3383
...   ...           ...        ...            ...              ...
1320  NaN  1.718901e+09          4         0.4277           0.5346
1321  NaN  1.718901e+09          4         0.4400           0.5500
1322  NaN  1.718901e+09          4         0.4657           0.5821
1323  NaN  1.718901e+09          4         0.4780           0.5975
1324  NaN  1.718901e+09          4         0.5037           0.6296

      cpu_active_servers  bandwidth_utilization  bw_active_links  \
1                 0.0156                 0.1362           0.0333
2                 0.0467                 0.4085           0.0333
3                 0.0485                 0.4247           0.0333
4                 0.0797                 0.6970           0.0333
5                 0.0815                 0.7132           0.0333
...                  ...                    ...              ...
1320              0.2579                 0.5642           0.4800
1321              0.2598                 0.5682           0.5200
1322              0.2726                 0.5963           0.5200
1323              0.2790                 0.6103           0.5600
1324              0.2998                 0.6559           0.5600

      cache_utilization  cache_active_servers  ...       depart_time  \
1                0.4000                0.0103  ...    sfc_cache_p1_1
2                0.4000                0.0317  ...   sfc_unique_p1_1
3                0.4000                0.0333  ...    sfc_cache_p2_1
4                0.4000                0.0547  ...   sfc_unique_p2_1
5                0.4000                0.0564  ...    sfc_cache_p3_1
...                 ...                   ...  ...               ...
1320             0.6857                0.3564  ...  sfc_unique_p2_50
1321             0.7429                0.3667  ...   sfc_cache_p3_50
1322             0.7429                0.3881  ...  sfc_unique_p3_50
1323             0.8000                0.3983  ...   sfc_cache_p4_50
1324             0.8000                0.4197  ...  sfc_unique_p4_50

         sfc_id  cpu_saved  cache_saved  shared_vnfs  running_sfcs  \
1      0.000000        0.0            0            1             1
2      0.000000        0.0            1            2             1
3     10.333333       40.0            4            3             2
4     10.333333       40.0            5            4             2
5     20.666667       80.0            8            5             3
...         ...        ...          ...          ...           ...
1320  52.000000      160.0           21           27            16
1321  52.000000      160.0           21           28            17
1322  52.000000      160.0           21           29            17
1323  52.000000      160.0           22           30            18
1324  52.000000      160.0           23           31            18

      running_players running_sessions  server_crashed  trascode_bw
1                   1                0       32.333333            0
2                   1                0       64.666667            0
3                   1                0       32.333333            0
4                   1                0       64.666667            0
5                   1                0       32.333333            0
...               ...              ...             ...          ...
1320                5                0       64.666667            4
1321                5                0       32.333333            4
1322                5                0       64.666667            4
1323                5                0       32.333333            4
1324                5                0       64.666667            4

[1324 rows x 27 columns]
      No.          time  timestamp  number_of_sfc  cpu_utilization  \
1     NaN  1.718900e+09          4         0.0103           0.0617
2     NaN  1.718900e+09          4         0.0317           0.1900
3     NaN  1.718900e+09          4         0.0333           0.2000
4     NaN  1.718900e+09          4         0.0547           0.3283
5     NaN  1.718900e+09          4         0.0564           0.3383
...   ...           ...        ...            ...              ...
1364  NaN  1.718901e+09          4         0.4389           0.9875
1365  NaN  1.718901e+09          4         0.4411           0.9925
1366  NaN  1.718901e+09          4         0.4696           1.0567
1367  NaN  1.718901e+09          4         0.4719           1.0617
1368  NaN  1.718901e+09          4         0.4719           1.0617

      cpu_active_servers  bandwidth_utilization  bw_active_links  \
1                 0.0156                 0.1362           0.0333
2                 0.0467                 0.4085           0.0333
3                 0.0485                 0.4247           0.0333
4                 0.0797                 0.6970           0.0333
5                 0.0815                 0.7132           0.0333
...                  ...                    ...              ...
1364              0.1175                 0.4112           0.1778
1365              0.1212                 0.4241           0.1778
1366              0.1286                 0.4500           0.1778
1367              0.1323                 0.4629           0.1778
1368              0.1323                 0.4629           0.1778

      cache_utilization  cache_active_servers  ...       depart_time  \
1                0.4000                0.0103  ...    sfc_cache_p1_1
2                0.4000                0.0317  ...   sfc_unique_p1_1
3                0.4000                0.0333  ...    sfc_cache_p2_1
4                0.4000                0.0547  ...   sfc_unique_p2_1
5                0.4000                0.0564  ...    sfc_cache_p3_1
...                 ...                   ...  ...               ...
1364             0.5333                0.3292  ...  sfc_unique_p2_50
1365             0.5333                0.3308  ...   sfc_cache_p3_50
1366             0.5333                0.3522  ...  sfc_unique_p3_50
1367             0.5333                0.3539  ...   sfc_cache_p4_50
1368             0.5333                0.3539  ...  sfc_unique_p4_50

         sfc_id  cpu_saved  cache_saved  shared_vnfs  running_sfcs  \
1      0.000000        0.0            0            1             1
2      0.000000        0.0            1            2             1
3     10.333333       40.0            4            3             2
4     10.333333       40.0            5            4             2
5     20.666667       80.0            8            5             3
...         ...        ...          ...          ...           ...
1364  62.000000      240.0           27           23            13
1365  72.333333      280.0           30           24            14
1366  72.333333      280.0           31           25            14
1367  82.666667      320.0           34           26            15
1368  82.666667      320.0           34           26            15

      running_players running_sessions  server_crashed  trascode_bw
1                   1                0       32.333333            0
2                   1                0       64.666667            0
3                   1                0       32.333333            0
4                   1                0       64.666667            0
5                   1                0       32.333333            0
...               ...              ...             ...          ...
1364                5                0       64.666667            8
1365                5                0       32.333333            8
1366                5                0       64.666667            8
1367                5                0       32.333333            8
1368                5                0       64.666667            8

[1368 rows x 27 columns]
      No.          time  timestamp  number_of_sfc  cpu_utilization  \
1     NaN  1.718900e+09          4         0.0103           0.0617
2     NaN  1.718900e+09          4         0.0317           0.1900
3     NaN  1.718900e+09          4         0.0333           0.2000
4     NaN  1.718900e+09          4         0.0547           0.3283
5     NaN  1.718900e+09          4         0.0564           0.3383
...   ...           ...        ...            ...              ...
1369  NaN  1.718901e+09          4         0.4822           0.7233
1370  NaN  1.718901e+09          4         0.4839           0.7258
1371  NaN  1.718901e+09          4         0.5053           0.7579
1372  NaN  1.718901e+09          4         0.5069           0.7604
1373  NaN  1.718901e+09          4         0.5053           0.6737

      cpu_active_servers  bandwidth_utilization  bw_active_links  \
1                 0.0156                 0.1362           0.0333
2                 0.0467                 0.4085           0.0333
3                 0.0485                 0.4247           0.0333
4                 0.0797                 0.6970           0.0333
5                 0.0815                 0.7132           0.0333
...                  ...                    ...              ...
1369              0.2557                 0.6884           0.3667
1370              0.2575                 0.6933           0.3667
1371              0.2612                 0.7033           0.3667
1372              0.2631                 0.7083           0.3667
1373              0.2375                 0.6394           0.3667

      cache_utilization  cache_active_servers  ...       depart_time  \
1                0.4000                0.0103  ...    sfc_cache_p1_1
2                0.4000                0.0317  ...   sfc_unique_p1_1
3                0.4000                0.0333  ...    sfc_cache_p2_1
4                0.4000                0.0547  ...   sfc_unique_p2_1
5                0.4000                0.0564  ...    sfc_cache_p3_1
...                 ...                   ...  ...               ...
1369             0.6286                0.4822  ...  sfc_unique_p2_50
1370             0.6286                0.4839  ...   sfc_cache_p3_50
1371             0.6286                0.5053  ...  sfc_unique_p3_50
1372             0.6286                0.5069  ...   sfc_cache_p4_50
1373             0.6286                0.5053  ...  sfc_unique_p4_50

         sfc_id  cpu_saved  cache_saved  shared_vnfs  running_sfcs  \
1      0.000000        0.0            0            1             1
2      0.000000        0.0            1            2             1
3     10.333333       40.0            4            3             2
4     10.333333       40.0            5            4             2
5     20.666667       80.0            8            5             3
...         ...        ...          ...          ...           ...
1369  67.333333      240.0           34           34            18
1370  77.666667      280.0           37           35            19
1371  77.666667      280.0           37           36            19
1372  88.000000      320.0           40           37            20
1373  77.666667      280.0           36           36            19

      running_players running_sessions  server_crashed  trascode_bw
1                   1                0       32.333333            0
2                   1                0       64.666667            0
3                   1                0       32.333333            0
4                   1                0       64.666667            0
5                   1                0       32.333333            0

In [24]:
print(aggregated_simulation_data)

Empty DataFrame
Columns: []
Index: []

### Criação de colunas extras

Aqui devem ser criadas as métricas novas a partir de outras, como por exemplo CPU consumida por Fluxo

In [20]:
aggregated_simulation_data["CPU Salva por Fluxo"] = (
    aggregated_simulation_data["cpu_saved"] / aggregated_simulation_data["running_sfcs"]
)
aggregated_simulation_data["CPU Salva por Servidor"] = aggregated_simulation_data["cpu_saved"] / 35

aggregated_simulation_data["Cache Salva por Fluxo"] = (
    aggregated_simulation_data["cache_saved"] / aggregated_simulation_data["running_sfcs"]
)
aggregated_simulation_data["Cache Salva por Servidor"] = (
    aggregated_simulation_data["cache_saved"] / 35
)

aggregated_simulation_data["CPU por Fluxo"] = (
    aggregated_simulation_data["cpu_utilization"] / aggregated_simulation_data["running_sfcs"]
)
aggregated_simulation_data["Cache por Fluxo"] = (
    aggregated_simulation_data["cache_utilization"] / aggregated_simulation_data["running_sfcs"]
)
aggregated_simulation_data["Banda por Fluxo"] = (
    aggregated_simulation_data["bandwidth_utilization"]
    / aggregated_simulation_data["running_sfcs"]
)

# Usuários mal servidos: 0
# Usuários bem servidos: 1
aggregated_simulation_data["servido"] = aggregated_simulation_data["latency"].apply(
    lambda x: 1 if 0 <= x <= 6 else 0
)

KeyError: 'cpu_saved'

### Fase de agrupamento dos dados

As simulações estão concatenadas verticalmente, precisamo tirar agora uma média geral dessas simulações, agrupando por algoritmo e também pela reliability

In [7]:
# Agrupar os dados por algoritmo e confiabilidade
grouped = aggregated_simulation_data.groupby(["algorithm", "reliability", "tempo"]).mean()
grouped

                             cpu_utilization  cache_utilization  \
algorithm reliability tempo
ga        0.95        0             0.030028           0.031900
                      1             0.044868           0.040425
                      2             0.044006           0.046475
                      3             0.078269           0.075350
                      4             0.075785           0.062883
...                                      ...                ...
osfem     0.99        995           0.626000           0.415700
                      996           0.622945           0.411200
                      997           0.624820           0.411200
                      998           0.633295           0.414450
                      999           0.624570           0.411575

                             bandwidth_utilization  cpu_resilient  \
algorithm reliability tempo
ga        0.95        0                   0.012124       0.030028
                      1                   0.011995       0.044868
                      2                   0.013855       0.044006
                      3                   0.027585       0.078269
                      4                   0.028787       0.075785
...                                            ...            ...
osfem     0.99        995                 0.102090       0.562745
                      996                 0.116182       0.558165
                      997                 0.103113       0.561830
                      998                 0.110607       0.569045
                      999                 0.105353       0.562285

                             cache_resilient  bw_resilient   success  \
algorithm reliability tempo
ga        0.95        0             0.031900      0.012124  1.000000
                      1             0.040425      0.011995  1.000000
                      2             0.046475      0.013855  1.000000
                      3             0.075350      0.027585  1.000000
                      4             0.062883      0.028787  1.000000
...                                      ...           ...       ...
osfem     0.99        995           0.374000      0.112160  0.997374
                      996           0.367125      0.101452  0.997376
                      997           0.369875      0.102283  0.997377
                      998           0.371250      0.115998  0.997380
                      999           0.369875      0.105353  0.997380

                              latency  duration  running_sfcs  ...  \
algorithm reliability tempo                                    ...
ga        0.95        0      2.200000  0.177219          2.84  ...
                      1      1.490000  0.188888          3.38  ...
                      2      1.850000  0.181434          3.40  ...
                      3      1.650000  0.173734          6.24  ...
                      4      1.856667  0.178457          5.82  ...
...                               ...       ...           ...  ...
osfem     0.99        995    1.175000  0.000699         49.80  ...
                      996    1.250000  0.000499         49.65  ...
                      997    1.450000  0.000647         49.90  ...
                      998    1.350000  0.000698         50.25  ...
                      999    1.100000  0.000598         49.65  ...

                             shared_vnfs  server_crashed  CPU Salva por Fluxo  \
algorithm reliability tempo
ga        0.95        0             2.04             0.0             1.636364
                      1             0.58             0.0             0.138889
                      2             0.78             0.0             0.000000
                      3             2.54             0.0             0.486253
                      4             2.89             0.0             0.532634
...                                  ...             ...                  ...
osfem     0.99        995          56.45             0.0             1.891055
                      996          56.90             0.0             1.930990
                      997          57.50             0.0             1.944504
                      998          57.40             0.0             1.906408
                      999          56.70             0.0             1.887891

                             CPU Salva por Servidor  Cache Salva por Fluxo  \
algorithm reliability tempo
ga        0.95        0                    0.133333               6.480000
                      1                    0.011905               0.550000
                      2                    0.000000               0.000000
                      3                    0.089524               1.758362
                      4                    0.096667               1.269231
...                                             ...                    ...
osfem     0.99        995                  2.690000               7.524327
                      996                  2.737619               7.682849
                      997                  2.773333               7.736746
                      998                  2.737619               7.585125
                      999                  2.701905               7.519490

                             Cache Salva por Servidor  CPU por Fluxo  \
algorithm reliability tempo
ga        0.95        0                      0.528000       0.010564
                      1                      0.047143       0.013247
                      2                      0.000000       0.012941
                      3                      0.330000       0.012513
                      4                      0.235714       0.013111
...                                               ...            ...
osfem     0.99        995                   10.701429       0.012589
                      996                   10.890000       0.012560
                      997                   11.031429       0.012540
                      998                   10.890000       0.012624
                      999                   10.748571       0.012634

                             Cache por Fluxo  Banda por Fluxo  servido
algorithm reliability tempo
ga        0.95        0             0.011300         0.004266      1.0
                      1             0.011951         0.003589      1.0
                      2             0.013675         0.004035      1.0
                      3             0.012284         0.004446      1.0
                      4             0.010783         0.004869      1.0
...                                      ...              ...      ...
osfem     0.99        995           0.008361         0.002046      1.0
                      996           0.008287         0.002317      1.0
                      997           0.008261         0.002057      1.0
                      998           0.008266         0.002184      1.0
                      999           0.008382         0.002107      1.0

[12000 rows x 24 columns]

In [8]:
# Caso queira acessa um algoritmo com alguma reliability específica:
# filtered_group = final_grouped_data.xs(('osfem', 0.95), level=['algorithm', 'reliability'])
# filtered_group

# Gráfico 1 <a id="gr1"></a>

Nesse caso queremos uma média da simulação inteira e não uma análise ao longo do tempo, portanto usaremos o seguinte agrupamento:

In [9]:
grouped_df = aggregated_simulation_data.groupby(["algorithm", "reliability"]).mean().reset_index()
grouped_df

,algorithm,reliability,tempo,cpu_utilization,cache_utilization,bandwidth_utilization,cpu_resilient,cache_resilient,bw_resilient,success,...,shared_vnfs,server_crashed,CPU Salva por Fluxo,CPU Salva por Servidor,Cache Salva por Fluxo,Cache Salva por Servidor,CPU por Fluxo,Cache por Fluxo,Banda por Fluxo,servido
0,ga,0.95,499.5,0.585837,0.533550,0.143195,0.374399,0.342435,0.143195,0.923652,...,18.440797,0.003167,0.880647,0.794472,3.188801,2.885121,0.019685,0.017662,0.004704,0.993800
1,ga,0.975,499.5,0.523300,0.510725,0.169091,0.443761,0.432929,0.169091,0.950982,...,21.558693,0.001833,0.887236,0.937440,3.169440,3.318009,0.014120,0.013710,0.004561,0.995800
2,ga,0.99,499.5,0.516318,0.486030,0.172828,0.472658,0.445061,0.172828,0.966034,...,24.842623,0.000867,0.990280,1.133063,3.521913,4.042085,0.013004,0.012272,0.004338,0.999600
3,msf,0.95,499.5,0.662089,0.538459,0.226507,0.478258,0.388329,0.226507,0.941790,...,26.937646,0.002133,1.107707,1.168468,4.175248,4.372029,0.016905,0.013598,0.005708,0.972500
4,msf,0.975,499.5,0.531333,0.420925,0.195187,0.458137,0.361514,0.195187,0.971211,...,36.578507,0.004100,1.530060,1.686784,5.778183,6.352767,0.013440,0.010545,0.004876,0.991000
5,msf,0.99,499.5,0.548558,0.447707,0.185071,0.467975,0.380633,0.185071,0.973901,...,35.641967,0.001100,1.466842,1.632130,5.502115,6.104808,0.013603,0.010987,0.004542,0.987800
6,musfico,0.95,499.5,0.722899,0.586758,0.202181,0.495309,0.395093,0.202181,0.929877,...,42.348807,0.002500,1.507341,1.824787,5.913167,7.149953,0.016883,0.013514,0.004690,0.964000
7,musfico,0.975,499.5,0.573477,0.438358,0.179569,0.472247,0.359142,0.179569,0.976716,...,43.789877,0.002867,1.675290,1.938261,6.470542,7.495708,0.013939,0.010514,0.004288,0.972400
8,musfico,0.99,499.5,0.736586,0.631408,0.236723,0.612321,0.519366,0.236723,0.909143,...,47.962767,0.001800,1.417157,1.998566,5.504775,7.761279,0.013840,0.011548,0.004437,0.972200
9,osfem,0.95,499.5,0.672165,0.470052,0.118375,0.475100,0.326893,0.118462,0.993012,...,45.254126,0.001735,1.865263,2.230717,7.402184,8.855118,0.015931,0.011165,0.002764,0.998625
10,osfem,0.975,499.5,0.608837,0.400556,0.108587,0.490866,0.320605,0.108676,0.996945,...,48.443259,0.002174,1.928062,2.389526,7.665048,9.497513,0.013894,0.009144,0.002445,0.998700
11,osfem,0.99,499.5,0.540910,0.342730,0.093261,0.496474,0.313489,0.093323,0.998431,...,52.064594,0.002025,2.045537,2.581732,8.111347,10.240641,0.012109,0.007669,0.002056,1.000000

In [16]:
def plot_metric_1(grouped_df, metric, algorithms=None):
    """
    Função para plotar um gráfico de barras para uma métrica específica e algoritmos selecionados.

    Parâmetros:
    - grouped_df: DataFrame agrupado com as métricas.
    - metric: Métrica a ser plotada (e.g., 'cpu_utilization', 'cache_utilization').
    - algorithms: Lista de algoritmos a serem mostrados (opcional). Se None, mostra todos os algoritmos.
    """
    if algorithms:
        filtered_df = grouped_df[grouped_df["algorithm"].isin(algorithms)]
    else:
        filtered_df = grouped_df

    fig = px.bar(
        filtered_df,
        x="reliability",
        y=metric,
        color="algorithm",
        barmode="group",
        title=f"{metric.replace('_', ' ').title()} vs Reliability",
    )

    fig.update_layout(xaxis_title="Reliability", yaxis_title=metric.replace("_", " ").title())

    fig.show()

In [17]:
# Exemplo de uso da função
plot_metric_1(grouped_df, "success", algorithms=["musfico", "msf", "ga", "osfem"])
plot_metric_1(grouped_df, "cpu_resilient", algorithms=["musfico", "msf", "ga", "osfem"])
plot_metric_1(grouped_df, "cache_resilient", algorithms=["musfico", "msf", "ga", "osfem"])
plot_metric_1(grouped_df, "bw_resilient", algorithms=["musfico", "msf", "ga", "osfem"])

# Gráfico 2 <a id="gr2"></a>

In [11]:
# TODO ainda não desenvolvido

# Gráfico 3 <a id="gr3"></a>

In [12]:
# TODO ainda não desenvolvido

# Gráfico 4 <a id="gr4"></a>

In [13]:
# TODO ainda não desenvolvido